import { createWebsiteTool } from './tools/website/createWebsite.js';

// Test with the exact HTML that was generated by the AI
const truncatedHtml = `<!DOCTYPE html>
<html>
<head>
    <title>Simulador de Apuestas con Gato</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f0f0f0;
            text-align: center;
        }
        .container {
            width: 80%;
            margin: 0 auto;
            padding: 20px;
            background-color: #fff;
            border-radius: 8px;
            box-shadow: 0 0 10px rgba(0, 0, 0, 0.1`;

async function testTruncatedHtml() {
  console.log('Testing create_website tool with truncated HTML...');
  console.log('Input HTML length:', truncatedHtml.length);
  console.log('HTML ends with:', truncatedHtml.slice(-50));

  try {
    const result = await createWebsiteTool.execute({
      name: 'test_truncated',
      html: truncatedHtml,
      description: 'Test truncated HTML',
    });

    console.log('Tool execution result:', result);

    // Check what was actually saved
    const fs = await import('fs');
    const savedHtml = fs.readFileSync('./websites/test_truncated.html', 'utf8');
    console.log('Saved HTML length:', savedHtml.length);
    console.log('Saved HTML ends with:', savedHtml.slice(-50));
  } catch (error) {
    console.error('Tool execution failed:', error);
  }
}

testTruncatedHtml();
